[package]
name = "hir"
version = "0.1.0"
edition = "2024"

[dependencies]
smol_str = "0.3.2"
la-arena = "0.3.1"
syntax = { path = "../syntax" }
ast = { path = "../ast" }

[dev-dependencies]
parser = { path = "../parser" }
