[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
drop_bomb = "0.1.5"
lexer = { path = "../lexer" }
syntax = { path = "../syntax" }
rowan = "0.16.1"

[dev-dependencies]
expect-test = "1.5.1"
